MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.16

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,39 +4,61 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "qngQGzM48j3Ai/d7Mz6Q1jpXgjKjYHWBFpahKSr1dYJgZmgHAGoOQ3ZTufC5YSMND8aMGbxVW7iw6OnG8THQUKkzDlq9GCjlc9zrCAhgGOCzkcUCSdX7hxvfUWsmcK+Grcy3wQ6PN1/ueGszU2yoyxQxq/9qv1KMdd9ebw07oZKDgBwHSFjy1tD+ex/SIna9Vl23YxcAVp7wiXpMdK8fau+MjeW3YO7nQBjHY8yzamOOYwuxiV2uxDRGUDNYioZ0uB2Dks5yD3WCT0o+G3ee+SK5lUO1iLLZxUYtgqukX/5xqVFjkXNjs4l2JwHjfNE9Y/zv26B3NvQf1Dfn1hTxTqJqD06pPDDmKfXG3IyCzA5XyIGsloo6iUwnBw0uWozqyC+QeFmrAyyCMBDSLPQBkeWEHaF1VRs2p9GB9h/UYDOq5wLpNpJF0U8/Gz86npWHTImv+UYNioYTZRDquH4dpoHP5XKhwIwrwFPHR3L289bVEQZ3qceNCHjiwyLOMuuKP8TUSO7lTLBByuvVW1QVJT51k4iiQv/AWmqKxm6EDDSQ0OizkwOmsrMp4yzjChpB+rMr3ELmCKTnM893W3j5kIBYXYjzHOWCWIOMjSQXXeqvb27EYFByC9A+KPnm7mmXPGwbLWAHl4V8ZTIHb5pFcm8SG2Nc93W7HxvlqfzblXc="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
-      MINICONDA_URL="http://repo.continuum.io/miniconda"
+      echo ""
+      echo "Installing a fresh version of Miniconda."
+      MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
-      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
+      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
